[package]
name = "cli_driver"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
axum = "0.8"
mime = "0.3"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["io-util", "macros", "net", "rt", "signal", "sync"] }
usecase = { path = "../../libs/usecase" }
serde_json = "1"

[dev-dependencies]
serde_json = "1"
tower = { version = "0.5", features = ["util"] }
